#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

# Install nginx
apt-get -y update
apt-get -y install nginx

# Create sample file
echo "Hello World!" > /var/www/html/index.html

# Create error file
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# add the following configuration to the existing server block
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header p/X-Served-By: \"$HOSTNAME\";/" /etc/nginx/nginx.com

# restart nginx
service nginx restart
