#!/usr/bin/env bash
# Bash script that configures Nginx server with a custom header

# Install nginx
apt-get -y update
apt-get -y install nginx

# Create sample file
echo "Hello World" > /var/www/html/index.html

# Create error file
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# add the following configuration to the existing server block
string_for_replacement="server_name_;\n\trewrite ^\redirect_me https\/\/www.google.com permanent;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/"
sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-available/default

sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By: \"$HOSTNAME\";/" /etc/nginx/nginx.conf

# restart nginx
service nginx restart
