#!/usr/bin/env bash
# Bah script to install load balancer
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\* 

sudo sed -i 's/^\(.*\)frontend.*$/\1frontend http_frontend\nbind *:80\nmode http\ndefault_backend http_backend/' /etc/haproxy/haproxy.cfg
sudo echo -e "\nbackend http_backend\nmode http\nbalance roundrobin\nserver 157540-web-01 18.234.129.117:80 check\nserver 157540-web-02 100.25.22.89:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
