#!/usr/bin/env bash
# Bah script to install load balancer
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\* 
default_backend web-backend\n\nbackend web-backend
echo -e "\nfrontend http\n\tbin *:80\n\tmode http\n\tbalance roundrobin\n\tdefault_backend web-backend\n\tbackend web-backend\n\tserver 157540-web-01 18.234.129.117:80 check\n\tserver 157540-web-02 100.25.22.89:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
