#!/usr/bin/env bash
# Bah script to install load balancer

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\* 

sudo echo -e "
frontend http_frontend
	bind *:80
	default_backend http_backend

backend http_backend
	balance roundrobin
	server 157540-web-01 18.234.129.117:80 check
	server 157540-web-02 100.25.22.89:80 check
" >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
